### ISSUE TITLE
dude its not working

### ISSUE THREAD

**Issue by AvraMx** [sandarshsridhar/wiz-spotify-connected#26]
i did every thing you say and when i playing song on my spotify app the light dont work

**Comment by AvraMx** [comment]
TypeError: this.fileHandler.createWriteStream is not a function
and then⚡️[server]: Server is running at http://localhost:8888

**Comment by sandarshsridhar** [comment]
Hey, I think it's got to do with your Node version. Update the version to >16 and try again.

**Comment by sandarshsridhar** [comment]
@AvraMx, did it resolve the issue?

**Comment by sandarshsridhar** [comment]
I am going to close this issue as I have not received any traction after my comments. Feel free to create a new one for any further issues.
