### ISSUE TITLE
Getting some promises issue

### ISSUE THREAD

**Issue by necromancerthedark** [sandarshsridhar/wiz-spotify-connected#39]
Things I have done:
- Got my Spotify credentials 
- Created `.env` file
- ran `npm i`
- ran `npm run start`

My node version is v22.6.0 

![image](https://github.com/user-attachments/assets/20de283a-797b-4b5d-80a3-5ae6836cf52a)

also tried with v18.0.0
![image](https://github.com/user-attachments/assets/e60b0c4f-a848-4369-827c-48715e74375d)

what could be issue here?

**Comment by sandarshsridhar** [comment]
@necromancerthedark, it's not a promise issue. Your system has access issues to create the log file. It's a very simple fix. Just create a file manually called debug-logs.txt in the location specified in the image and you should be set.

**Comment by necromancerthedark** [comment]
Sorry, my bad for not reading README.md completely! /s
